# This YAML file describes your package. Stack will automatically generate a
# Cabal file when you run `stack build`. See the hpack website for help with
# this file: <https://github.com/sol/hpack>.
benchmarks:
  clott-benchmarks:
    dependencies:
    - base
    - clott
    - criterion
    ghc-options:
    - -rtsopts
    - -threaded
    - -fprof-auto
    - -fprof-cafs
    - "\"-with-rtsopts=-p -s\""
    main: Main.hs
    source-dirs: benchmark
category: Other
description: clott is a language for guarded FRP using clocked type theory.
executables: {}
  # clott:
  #   dependencies:
  #   - base
  #   - clott
  #   ghc-options:
  #   - -rtsopts
  #   - -threaded
  #   - -with-rtsopts=-N
  #   main: Main.hs
  #   source-dirs: executable
extra-source-files:
- CHANGELOG.md
- LICENSE.md
- package.yaml
- README.md
- stack.yaml
ghc-options: -Wall
github: adamschoenemann/clott
library:
  dependencies:
  - base
  - parsec
  - template-haskell
  - containers
  source-dirs: library
license: MIT
maintainer: Adam Schønemann
name: clott
synopsis: A DSL for FRP based on Clocked Type Theory.
tests:
  clott-test-suite:
    dependencies:
    - base
    - clott
    - tasty
    - tasty-hspec
    - parsec
    - containers
    - neat-interpolation
    ghc-options:
    - -rtsopts
    - -threaded
    - -with-rtsopts=-N
    main: Main.hs
    source-dirs: test-suite
version: '0.0.0'
ghc-options: -Wall -Wno-unticked-promoted-constructors -fno-warn-unused-matches -fno-warn-unused-imports
dependencies:
  - mtl
  - prettyprinter
  - text
  - deepseq